// Generated by CoffeeScript 1.12.4
(function() {
  var Gist, bind, main, preview, sidebar;

  bind = rx.bind;

  rx.rxt.importTags();

  Gist = (function() {
    function Gist(id, desc, files) {
      this.id = id;
      this.desc = desc;
      this.files = files;
    }

    return Gist;

  })();

  sidebar = function(args) {
    var currentGist, gists;
    gists = args.gists;
    currentGist = args.currentGist;
    return div({
      "class": 'sidebar'
    }, [
      ul({}, gists.map(function(g) {
        return li({
          "class": "" + (g === currentGist.get() ? 'selected' : ''),
          click: function() {
            return currentGist.set(g);
          }
        }, g.desc);
      }))
    ]);
  };

  preview = function(args) {
    var currentGist, gists;
    gists = args.gists;
    currentGist = args.currentGist;
    return div({
      "class": 'preview'
    }, [
      h3({}, bind(function() {
        return currentGist.get().desc;
      })), div({}, bind(function() {
        var file, fileName, ref, results;
        ref = currentGist.get().files;
        results = [];
        for (fileName in ref) {
          file = ref[fileName];
          results.push((function(fileName, file) {
            var fileContent;
            fileContent = rx.cell('');
            $.ajax({
              url: file.raw_url,
              success: function(data) {
                return fileContent.set(data);
              }
            });
            return div({}, [
              pre({}, fileName), code({}, bind(function() {
                return fileContent.get();
              }))
            ]);
          })(fileName, file));
        }
        return results;
      }))
    ]);
  };

  main = function(args) {
    var $base, gistsAll, loadFromGithub;
    gistsAll = rx.array([]);
    loadFromGithub = function() {
      return $.ajax({
        url: 'https://api.github.com/users/drbelfast/gists',
        success: function(data) {
          return gistsAll.replace(data.map(function(g) {
            return new Gist(g.id, g.description, g.files);
          }));
        }
      });
    };
    loadFromGithub();
    $base = div({
      "class": 'hi'
    }, [
      h1('hello'), div({
        "class": 'container'
      }, bind(function() {
        var currentGist;
        if (gistsAll.length() > 0) {
          currentGist = rx.cell(gistsAll.at(0));
          return [
            sidebar({
              gists: gistsAll,
              currentGist: currentGist
            }), preview({
              gists: gistsAll,
              currentGist: currentGist
            })
          ];
        } else {
          return [div({}, 'Loading...')];
        }
      }))
    ]);
    return $base;
  };

  $('body').append(main);

}).call(this);
